version: '3'
services:
  db:
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017

  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db